### ISSUE TITLE
Adapt to max_value plot

### ISSUE THREAD

**Issue by AllanCFE** [vicenteke/str#3]
- [x] For loop for "case" isn't needed anymore
- [x] generateTaskSet now only have 1 argument. Delete the second argument from the calls
- [ ] plotGraph cases now are based on utilization, change labels

**Comment by vicenteke** [comment]
Dei uma olhada nesse novo branch o "max_value_plot", mas não entendi muito bem qual o resultado final. A ideia é fazer um plot só com tarefas de qualquer caso?

**Comment by AllanCFE** [comment]
O professor pediu uma coisa diferente
